### ISSUE TITLE
Hook.io problem

### ISSUE THREAD

**Issue by raditv** [rizaumami/merbot#10]
I have a problem when using hook.io

```
evalmachine.<anonymous>:9
  var textmessage =  msg.text;
                        ^
Cannot read property 'text' of undefined
```

that is error message

**Comment by rizaumami** [comment]
Make sure to:  
1. match `var TOKEN = hook.env.merbot_key;` and `var MASTER = hook.env.mimin_teh_bot;` with your key on [environmet variable](https://hook.io/env).
   ![environment variable](https://cloud.githubusercontent.com/assets/11420518/18979094/3bb94474-86f2-11e6-8dcd-0e56510cf990.png)
   `merbot_key` is my bot api token key, and `mimin_teh_bot` is my telegram-cli id key.
2. [start the bot webhook](https://core.telegram.org/bots/api#setwebhook)
