### ISSUE TITLE
help! i tried to install merbot but ..

### ISSUE THREAD

**Issue by kensukekita** [rizaumami/merbot#14]
i installed merbot it runs but never asked for phone number code or bot api key

`serpent 0.28-1 is now installed in /home/ubuntu/merbot/.luarocks (license: MIT)

Installing https://luarocks.org/multipart-post-1.1-1.src.rock
multipart-post 1.1-1 is now installed in /home/ubuntu/merbot/.luarocks (license: MIT/X11)

ubuntu@ip-172-31-10-185:~/merbot$ ./merbot
rm: cannot remove './telegram-cli/state': No such file or directory
Telegram-cli version 1.4.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `show_license' for details.
Telegram-cli uses libtgl version 2.1.0
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
[/home/ubuntu/merbot/.telegram-cli/downloads] created

 You are not logged in.
 Please log your bot in first, then restart merbot.

>
`

**Comment by kensukekita** [comment]
it's working now but i had another problem 
how to unlimit group creations?

**Comment by rizaumami** [comment]
This is a well known Telegram limitations. You cannot bulk/batch create groups. If you create too many group in a relatively short time, you're in a risk to be banned.
I think the limitation is on frequency, not count. So, you can create as many groups as you need as long as you give a pause between creation.

**Comment by kensukekita** [comment]
oh wow thanks your'e right!
