### ISSUE TITLE
google plugin not work.

### ISSUE THREAD

**Issue by afternewbie** [rizaumami/merbot#7]
Min,

i've installed your bot on my server and following all instruction.
but when i tried to use the google plugin and nothing happen, it's show this error on terminal.

`*** 1463736792.168528 lua: plugins/google.lua:23: attempt to index field 'responseData' (a nil value)
`

**Comment by rizaumami** [comment]
Yes. This is because of Google search API has been deprecated.

[What are the alternatives now that the Google web search API has been deprecated?](http://stackoverflow.com/questions/4082966/what-are-the-alternatives-now-that-the-google-web-search-api-has-been-deprecated)
