### ISSUE TITLE
I tried to install merbot but i faced this

### ISSUE THREAD

**Issue by ThisIsArman** [rizaumami/merbot#8]
Missing dependencies for oauth:
luacrypto

Error: Could not satisfy dependency: luacrypto
Error. Exiting.
root@vps:~/merbot# ./merbot

**Comment by rizaumami** [comment]
Please try again from scratch; It's works in my machine.
Perhaps the luarocks repository is down when you install `merbot`.

**Comment by ThisIsArman** [comment]
im tried in other days again this error

**Comment by rizaumami** [comment]
Starting from `v0.3`, merbot also provide a pre-compiled package so you don't have to compile it manually. Just download the pre-compiled package, extract then start to using it.
- install [dependencies](https://github.com/rizaumami/merbot/wiki/Bot-installation#dependencies) as usual
- download the latest release, i.e v0.3;  
  `wget https://github.com/rizaumami/merbot/releases/download/v0.3/merbot_0.3_amd64.tar.gz`
- extract the pre-compiled package using following command;  
  `tar xf merbot_0.3_amd64.tar.gz`
- enter extracted merbot folder;  
  `cd merbot`
- start merbot;  
  `./merbot`

Pre-compiled package is not portable yet, and it's only for 64 bit system. But, at least it will minimize compile time and down time of external resources.
