### ISSUE TITLE
Cannot read messages in supergroup with 200+ members

### ISSUE THREAD

**Issue by banghasan** [rizaumami/merbot#9]
Saya catatkan bugsnya di sini yak, sapa tau nanti ada patchnya bisa dikabari.

Bugs ada pada tgl-cli, yang mana dipakai juga oleh merbot ini. Yakni jika di dalam supergrup memiliki lebih dari 200 user. Pesan masuk, namun tidak dibaca olehnya sehingga tidak di respon.

**Comment by rizaumami** [comment]
_Rough translation:_

`tg-cli` bug: If a supergroup has more than 200 users, messages are received, but `tg-cli` unable to read (recognize/know) it so it's gave no responses.

Confirmed. This is telegram-cli bug.
